### ISSUE TITLE
Failed playback Nat Geo HD, Nat Geo Wild HD

### ISSUE THREAD

**Issue by rosenpapazov** [harrygg/plugin.video.vivatvgo#2]
Live playback silently fails without error notification for channels National Geographic HD and National Geographic Wild HD. 
Platform: LibreELEC 9.0.1 
Kodi 18.1
x86_64

**Comment by harrygg** [comment]
The only goal of the addon is to extract the play URL for the channels. From then on, the Kodi player kicks in and plays the live stream. As far as I see the addon has done its job and there are no issue with it.

**Comment by rosenpapazov** [comment]
Can confirm that it passed the URL to Kodi from logs. Will try to identify the playback issue elsewhere. 

Thanks for your great work!
